---
name: Set up environment

inputs:
  bazel-version:
    description: Bazel version
    required: true
  use-local-config-cc:
    description: Whether to use local_config_cc for C++ toolchain
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install Visual C++ Build Tools
      if: ${{ runner.os == 'Windows' && inputs.use-local-config-cc == 'true' }}
      uses: ilammy/msvc-dev-cmd@v1
    - name: Set environment variables to use Visual C++ in Bazel
      if: ${{ runner.os == 'Windows' && inputs.use-local-config-cc == 'true' }}
      shell: bash
      run: |
        echo "BAZEL_VC=${VCINSTALLDIR}" >> "${GITHUB_ENV}"
    - name: Set DEVELOPMENT_BAZEL_VERSION
      shell: bash
      run: |
        echo "DEVELOPMENT_BAZEL_VERSION=${BAZEL_VERSION}" >> "${GITHUB_ENV}"
      env:
        BAZEL_VERSION: ${{ inputs.bazel-version }}
    - name: Install bazelisk
      uses: yuyawk/github-actions/install-bazelisk@v1
