---
name: Set up environment

inputs:
  bazel-version:
    description: Bazel version
    required: true

runs:
  using: composite
  steps:
    - name: Generate .bazelversion
      shell: bash
      run: |
        echo "${BAZEL_VERSION}" > .bazelversion
        echo "${BAZEL_VERSION}" > examples/.bazelversion
      env:
        BAZEL_VERSION: ${{ inputs.bazel-version }}
    - name: Install bazelisk
      uses: yuyawk/github-actions/install-bazelisk@v1
