---
name: Set up environment

inputs:
  bazel-version:
    description: Bazel version
    required: true

runs:
  using: composite
  steps:
    - name: Generate .bazeliskrc
      shell: bash
      run: |
        echo ${{ inputs.bazel-version }} > .bazeliskrc
        echo ${{ inputs.bazel-version }} > examples/.bazeliskrc
    - name: Install bazelisk
      shell: bash
      run: |
        bazelisk_dir="$(realpath "$(mktemp -d -p .)")"
        wget https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64 \
          -O "${bazelisk_dir}/bazelisk"
        chmod +x "${bazelisk_dir}/bazelisk"
        echo "${bazelisk_dir}" >> "${GITHUB_PATH}"
