#ifndef TESTS_INTEGRATION_LOCAL_CONFIG_CC_WITH_EXTERNAL_INCLUDE_PATHS_EXTERNAL_LIBRARY_INCLUDE_FOO_BAR_HPP_
#define TESTS_INTEGRATION_LOCAL_CONFIG_CC_WITH_EXTERNAL_INCLUDE_PATHS_EXTERNAL_LIBRARY_INCLUDE_FOO_BAR_HPP_

namespace foo
{

    constexpr bool Bar() noexcept
    {
        return false;
    }

} // namespace foo

#endif // TESTS_INTEGRATION_LOCAL_CONFIG_CC_WITH_EXTERNAL_INCLUDE_PATHS_EXTERNAL_LIBRARY_INCLUDE_FOO_BAR_HPP_
