---
name: Set up environment

on:
  workflow_call:

jobs:
  set-up-environment:
    runs-on: ubuntu-22.04
    steps:
      - name: Install bazelisk
        run: |
          bazelisk_dir="$(realpath "$(mktemp -d -p .)")"
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64 \
            -O "${bazelisk_dir}/bazelisk"
          chmod +x "${bazelisk_dir}/bazelisk"
          echo "${bazelisk_dir}" >> "${GITHUB_PATH}"
