---
name: Run unit tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Install bazelisk
      run: |
        bazelisk_dir="$(realpath "$(mktemp -d -p .)")"
        wget https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64 \
          -O "${bazelisk_dir}/bazelisk"
        chmod +x "${bazelisk_dir}/bazelisk"
        echo "${bazelisk_dir}" >> "${GITHUB_PATH}"
    - name: Run unit tests
      run: ./execute_tests.sh
